config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: "homes#top"
  resources :postimages, only: [:new, :create, :index, :show, :destroy]
  resources :users, only: [:show, :edit, :update]
  get 'homes/about' => 'homes#about', as: 'about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/postimage.rb
class Postimage < ApplicationRecord

  has_one_attached :image
  belongs_to :user

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image/attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :postimages, dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    postimages_path
  end

  def after_sign_out_path_for(resource)
    about_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  
  end

  def about

  end
end

app/controllers/postimages_controller.rb
class PostimagesController < ApplicationController
  def new
    @postimage = Postimage.new
  end

  def create
    @postimage = Postimage.new(postimage_params)
    @postimage.user_id = current_user.id
    @postimage.save
    redirect_to postimages_path
  end

  def index
    @postimages = Postimage.all
  end

  def show
    @postimage = Postimage.find(params[:id])
  end

  def destroy
    postimage = Postimage.find(params[:id])
    postimage.destroy
    redirect_to postimages_path
  end

  private

  def postimage_params
    params.require(:postimage).permit(:shop_name, :image, :caption)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @postimages = @user.postimages
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/postimages_helper.rb
module PostimagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<h1>Aboutページ</h1>

app/views/homes/top.html.erb
<h1>Topページ</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meshiterro</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if user_signed_in? %>
        <li>
          <%= link_to "投稿フォーム", new_postimage_path %>
        </li>
        <li>
          <%= link_to "マイページ", user_path(current_user.id) %>
        </li>
        <li>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= link_to "新規登録", new_user_registration_path %>
        </li>
        <li>
          <%= link_to "ログイン", new_user_session_path %>
        </li>
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/postimages/index.html.erb
<% @postimages.each do |postimage| %>
  <div>
    <%= link_to postimage_path(postimage.id) do %>
      <%= image_tag postimage.get_image %>
    <% end %>
    <p>投稿ユーザー画面：<%= image_tag 'sample-author1.jpg' %></p>
    <p>ショップ名：<%= postimage.shop_name %></p>
    <p>説明：<%= postimage.caption %></p>
    <p>ユーザーネーム：<%= postimage.user.name %></p>
  </div>
<% end %>

app/views/postimages/new.html.erb
<h1>画像投稿フォーム</h1>
<%= form_with model: @postimage do |f| %>

  <h4>画像</h4>
  <%= f.file_field :image, accept: "image/*" %>
  <h4>ショップ名</h4>
  <%= f.text_field :shop_name %>
  <h4>説明</h4>
  <%= f.text_area :caption %>
  <%= f.submit '投稿' %>

<% end %>

app/views/postimages/show.html.erb
<div>
  <%= image_tag @postimage.get_image %>
  <p>ショップ名：<%= @postimage.shop_name %></p>
  <p>説明：<%= @postimage.caption %></p>
  <p>投稿ユーザー画面：<%= image_tag 'sample-author1.jpg' %></p>
  <p>ユーザーネーム：<%= @postimage.user.name %></p>
  <p>投稿日：<%= @postimage.created_at.strftime('%Y/%m/%d') %></p>
  <% if @postimage.user == current_user %>
    <%= link_to "削除", postimage_path(@postimage), method: :delete %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h2>プロフィール編集</h2>
<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前" %>
  <label for="inputImage">ProfileImage</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
  <%= f.submit "変更を保存" %>
<% end %>

app/views/users/show.html.erb
<div>
  <h3><%= @user.name %></h3>
  <%= image_tag @user.get_profile_image(100,100) %>
  <% if @user == current_user %>
    <p><%= link_to "プロフィール編集", edit_user_path(@user) %></p>
  <% end %>
</div>

<% @postimages.each do |postimage| %>
<div>
  <%= link_to postimage_path(postimage.id) do %>
    <%= image_tag postimage.get_image %>
  <% end %>
  <p>投稿ユーザー画面：<%= image_tag postimage.user.get_profile_image(100,100) %></p>
  <p>ショップ名：<%= postimage.shop_name %></p>
  <p>説明：<%= postimage.caption %></p>
  <p>ユーザーネーム：<%= postimage.user.name %></p>
</div>
<% end %>